#!/bin/bash
set -e

cd $(dirname $0)/..

rm -rf build/stage
mkdir -p build/stage
mkdir -p dist
pushd build/stage

BASE=$(echo ../*/output/target/)

mkdir -p usr/bin
mkdir -p usr/etc/ssl/certs/

cp ../../assets/ca-certificates.crt usr/etc/ssl/certs/
cp $BASE/bin/busybox usr/bin
cp $BASE/usr/bin/nsenter usr/bin/nsenter
cp $BASE/usr/sbin/xtables-legacy-multi usr/bin/iptables
cp $BASE/usr/bin/xz usr/bin/xz
cp $BASE/usr/bin/zstd usr/bin/zstd

ln -s busybox usr/bin/ps
ln -s busybox usr/bin/modprobe
ln -s busybox usr/bin/mount
ln -s busybox usr/bin/echo
ln -s busybox usr/bin/mkdir

tar cvzf ../../dist/artifacts/os-initrd-base-${1}.tar.gz .
